### ISSUE TITLE
Secondary servers should not expire records

### ISSUE THREAD

**Issue by pusateri** [pusateri/draft-pusateri-dnsop-update-timeout#15]
The primary should expire the records and NOTIFY the secondaries to pull down a new version of the database.

**Comment by timwattenberg** [comment]
I‘ll reopen this issue for discussion:
This behavior can result in unwanted results if the primary is down. Should we cover this case or is it considered out of scope.

@pusateri Can you quickly summarize your reasoning?

**Comment by pusateri** [comment]
This was described in an email but the basic rule is that there is only one primary server that changes the zone and all secondaries then receive the changes from the primary. If the primary goes down, the a secondary becomes the primary at some point and then performs the timeouts and sends these to the other secondaries.

**Comment by timwattenberg** [comment]
ACK.
