### ISSUE TITLE
Should TIMEOUT RR include TYPE?

### ISSUE THREAD

**Issue by pusateri** [pusateri/draft-pusateri-dnsop-update-timeout#17]
Mark Andrews comments:

I would add a covered type field to TIMEOUT (c.f. RRSIG).  I also wouldn’t have more than
a single timeout per record.  I’m tempted to say a single hash as well.  If there is multiple
timeouts per record then the blocks need to be sorted in timeout order.

Covered is there to reduce the number of RR’s that need to be hashed to remove a record.
It will also reduce the size of IXFR’s as you don’t need to re-construct a new TIMEOUT
record that covers every timeout at a name on each change.

For all records at a name is often more expensive that for all records of type covered.
Name servers are optimised for looking up <name,type,class> tuples rather than <name,class>
tuples.

**Comment by pusateri** [comment]
Adding a TYPE will reduce collisions and reduce the number of required hashes at the expense of adding more blocks (instances) and making a block 16-bits larger.

**Comment by timwattenberg** [comment]
I think we should follow Marks advice and add this. It might also result in more cases using NOHASH which kind of counteracts the expenses of the additional bits used.
