### ISSUE TITLE
Should we change the hash algorithm?

### ISSUE THREAD

**Issue by pusateri** [pusateri/draft-pusateri-dnsop-update-timeout#19]
Mark Andrews writes:

SHAKE128 does not meet these requirements.  In OPENSSL it is only
available in pre-release code.  It will be years before OPENSSL-1.1.1
is the OPENSSL release for most operating systems.

We (ISC) haven’t started working out what OPENSSL-1.1.1 breaks yet.
OPENSSL-1.1.0 broke lots of existing code.  Lots of code required
re-writing to work with OPENSSL-1.1.0 as it broke backwards compatibility
with OPENSSL-1.0.x.

Please pick hash algorithms that are already USED by DNS.  The results
can be truncated if you are worried about space.

**Comment by pusateri** [comment]
My response:

While I understand your point, OpenSSL 1.1.1 is the first release that will contain TLS 1.3. It is binary backward compatible with 1.1.0. Aside from our trivial use of SHAKE128, everyone is going to be upgrading to 1.1.1 as soon as possible to get TLS 1.3 support. See

https://wiki.openssl.org/index.php/TLS1.3

**Comment by pusateri** [comment]
Mark Andrews other comment:

And no it isn’t as easy as just calling OPENSSL.  PKCS#11 providers also need to support the hash algorithm.

**Comment by pusateri** [comment]
The only acceptable hash algorithms in PKCS#11 are the SHA-2 family such as SHA-256:

[Hashes in PKCS#11](https://cryptosense.com/blog/algorithm-choice-in-pkcs11-part-3-hash-functions/)

**Comment by pusateri** [comment]
Since we don't need 256 bits of digest, we could take the first 128 bits of SHA-256.

**Comment by pusateri** [comment]
OpenSSL 1.1.1 LTS was released on 11 Sept 2018. It is standard in the upcoming release of FreeBSD 12. Other operating systems will be incorporating it shortly. I don't think it is necessary to switch hash algorithms on the account of OpenSSL availability.

**Comment by pusateri** [comment]
Mark would like more discussion on this.

**Comment by rwfranks** [comment]
IMHO this RR should follow the pattern established by DS, not introduce anything new without some compelling justification for so doing.

Your earlier post [5 Sept 2018] is an interesting idea, but would require a redesign of the RDATA to allow for truncated hashes.

**Comment by timwattenberg** [comment]
Robert writes:

> I agree with Mark. Even the draft says:
> 
> 5.  Cryptographic Hash Requirements
> The cryptographic hash algorithm used SHOULD provide the following properties:
>     1.  Well known algorithm with implementations easily available
> 
> I have no objections to SHAKE128 being one of the supported algorithms, but one of the SHA-2 algorithms should be selected for MUST implement.

**Comment by pusateri** [comment]
The SHA-3 family of algorithms specifically takes into account the position of data being hashed in order to reduce collisions. The SHA-2 family of algorithms makes no such claim. This is important for A records when the RDATA is small and the order can be interchanged (128.1.10.1 vs 128.10.1.1)

**Comment by pusateri** [comment]
Are collisions more likely using the first 128 bits of SHA-256? Or the last 128 bits? I can't find any papers claiming it's ok to truncate the hash and the result is as good. Since 256 bytes is excessive, this is another compelling reason for SHAKE-128.
