### ISSUE TITLE
Multiple expiry times per RR vs multiple RRs

### ISSUE THREAD

**Issue by timwattenberg** [pusateri/draft-pusateri-dnsop-update-timeout#2]
In the current draft version of the draft (339ceed9078a6a766d6eb8955949390b25362db4), there are multiple hash lists in one TIMEOUT RR, each associating RRs with an expiry time.

If we would have only one expiry time per RR and would suggest using multiple RRs instead (similar to MX RRs), deleting/updating the expiry time would be more easy, because this would just mean deleting the RR.

**Comment by pusateri** [comment]
Doesn't this just move the problem? In the reverse direction, knowing which TIMEOUT RR is associated with another RR of the same owner name means that the server has to go through all of the TIMEOUT RRs to find the correct one.

**Comment by timwattenberg** [comment]
> Doesn't this just move the problem?

True. I think I was coming more from an _"What is the DNS-way of modeling this?"_ perspective, since it seems to be common to have multiple RRs in comparable cases (MX/NS/PTR, although this approach might has changed with the more recent DNS additions -> I'm not so familiar with them :wink:).

If you think implementation-wise it's generally more efficient to have them all in one RR, I'm perfectly fine with this approach.

**Comment by pusateri** [comment]
This is probably implementation dependent but we can leave this open and see what kind of comments we get back from DNS server experts before we decide.
