### ISSUE TITLE
Should we address TIMEOUT TTL?

### ISSUE THREAD

**Issue by timwattenberg** [pusateri/draft-pusateri-dnsop-update-timeout#20]
This came to my mind in context of #11 (and #8).
I think the answer is **no**.
The TTL of a TIMEOUT RR should not matter, because there’s no reason for clients to query this RR and the server itself also doesn’t need to use it in any way.

**Comment by pusateri** [comment]
The TTL of a TIMEOUT RR should be like any other TTL. TIMEOUT RRs might get queried. They might get cached in a resolver. The TTL is important to all of this. No reason to make TIMEOUT RRs any different in this respect.

I do think we should add some text to make this more clear if that isn't obvious.

**Comment by pusateri** [comment]
Can we close this given #13 pretty much covers it?
