### ISSUE TITLE
discuss third party record deletion through UPDATE

### ISSUE THREAD

**Issue by pusateri** [pusateri/draft-pusateri-dnsop-update-timeout#28]
A third party could monitor TIMEOUT records and when expiry time occurs, delete the represented records as well as the TIMEOUT records if the authoritative doesn't know how to handle TIMEOUT resource records.

**Comment by timwattenberg** [comment]
In fact this was something I had in mind as a project for the IETF 104 hackathon.

**Comment by pusateri** [comment]
What is your preferred language? What is your source of TIMEOUT records? I can update the Hackathon Wiki.
