### ISSUE TITLE
Have a "TIMEOUT is valid for all RRs under the owner" option

### ISSUE THREAD

**Issue by timwattenberg** [pusateri/draft-pusateri-dnsop-update-timeout#3]
If we add an option to specify that the chosen expiry time should be valid for all RRs under one owner, the RDATA hashing could be omitted in this case.

Choosing a `Hash Algorithm Index` and `Hash Count` of `0` might be a good fit for this behaviour?

**Comment by pusateri** [comment]
Yes, I think this is a good simplification. But since there are edge cases such as a hash count of 0 and an algorithm index not 0, maybe we should say that if the hash count is 0, the expiry time applies to all records and the algorithm index is ignored.

**Comment by pusateri** [comment]
Unfortunately, with the current Update Lease Lifetime proposal for Service Registration Protocol, the KEY record has a different lifetime than the other records and therefore, the hash would always be necessary. But other use cases like multiple PTR records for multiple names associated with an IP address could benefit from this.

**Comment by timwattenberg** [comment]
> Yes, I think this is a good simplification. [...]

I will add some text.

> Unfortunately, with the current Update Lease Lifetime proposal for Service Registration Protocol, the KEY record has a different lifetime than the other records [...]

Yes, I was aware of this but thought there might be fitting use cases nevertheless.

**Comment by pusateri** [comment]
You should also define an algorithm index of 0 as Unused for completeness.

**Comment by pusateri** [comment]
Also, the typical IETF way to do this is when the hash count is 0, to require the algorithm index to be set to 0 (Unused) on transmission and ignored on receipt.

**Comment by pusateri** [comment]
Fixed by Tim.
