### ISSUE TITLE
RR present in multiple TIMEOUT instances

### ISSUE THREAD

**Issue by timwattenberg** [pusateri/draft-pusateri-dnsop-update-timeout#5]
We might end up with RRs being present in multiple instances, potentially with different expiry times and hash values.

I suggest to mention at least that if an expiry time is reached an no RR matching a given hash value is present, the server should just continue with the next hash value.

Additionally we might want to specify a server behavior to avoid this situation by performing checks upon receiving a message resulting in an TIMEOUT RR (even though the source of the message is out of scope of the draft).

If you agree, I will add some text.

**Comment by pusateri** [comment]
Not sure I understand what you mean by "multiple instances". The hash value should uniquely identify a resource record.

Agree that we could mention some garbage collection if a hash value has no matching resource record but we should clearly state this is a bug and shouldn't occur under normal circumstances.

The last point still seems like garbage collection as a result of a previous bug.

**Comment by pusateri** [comment]
Oh, I see what you mean about instances. Explain how you could "end up with RRs being present in multiple instances, potentially with different expiry times and hash values". A subsequent DNS UPDATE should fail if the resource record already exists.

**Comment by timwattenberg** [comment]
Let's see...

An arbitrary RR is created through DNS UPDATE with an EDNS(0) lease time, so implicitly the server creates a TIMEOUT RR calculating the absolute expiry time and hashing the RR. Some time later (but before the expiry time is reached) the same RR is updated again, extending the EDNS(0) lease time (which is valid as I understand it). At this point we need to define the servers behavior, I think. 

I would suggest to let the server go through all instances (I hope the terminology is clear by now 😀), since the hash algorithm may has been changed in the meantime, an delete all hashes matching the RR whenever it is about to add/update a TIMEOUT RR.

**Comment by timwattenberg** [comment]
What do you think about this:

> Upon receiving any DNS UPDATE deleting RRs that might have been covered by a TIMEOUT RR, the server MUST go through all instances within the TIMEOUT RR and delete all hashes matching the relevant RR.

**Comment by pusateri** [comment]
I just don't see how the same RR could be in multiple instances. If an UPDATE occurs that affects an existing resource record, it can only delete/add. I don't think a change is possible. So to update the Expiry Time, you have to either wait for it to timeout and then add it again, or delete it and add it with a new timeout.

**Comment by timwattenberg** [comment]
> If an UPDATE occurs that affects an existing resource record, it can only delete/add. I don't think a change is possible. So to update the Expiry Time, you have to either wait for it to timeout and then add it again, or delete it and add it with a new timeout.

Right, but if a RR is deleted through UPDATE and the server doesn't go through the corresponding TIMEOUT also deleting the hash value, then this would leave a stale entry in the TIMEOUT. If the RR is added at any later point in time (potentially in the same UPDATE), the hash algorithm might has been changed in the meantime, so the stale entry could also be in another instance. 

That's what I meant with "one RR present in multiple TIMEOUT instances". (Although adding the RR at a later point in time would in most cases mean, that also some data was changed – so you are right, exactly the same RR in multiple instances is an unlikely scenario.)

But we should mention, that if the RR is deleted, the hash in the TIMEOUT should/must also be deleted (see comment above for my proposal) and suggest some graceful handling, if no RR matching the hash value is found, since the RR could also has been deleted by an uninformed sys admin "by hand" (e.g. editing the zone file), who didn't delete the corresponding entry in TIMEOUT.

**Comment by pusateri** [comment]
DNSOP email discussion about how an RR could be listed with multiple timeouts from different clients. Each timeout would have to be retained in case the most future one is deleted prematurely.
