### ISSUE TITLE
Add table of assigned hash algorithm identifiers to IANA section

### ISSUE THREAD

**Issue by timwattenberg** [pusateri/draft-pusateri-dnsop-update-timeout#6]
Index | Hash Algorithm | Length [Bits] | Comment
--- | --- | --- | ---
0 | NOHASH | | For use if no hashes are added to the TIMEOUT RR (all RRs under the owner shall expire)
1 | SHAKE128 | 128

(Feel free to edit this issue in order to extend/edit the table.)

**Comment by pusateri** [comment]
I don't want to provide SHA256 as an option. It has no real advantage over SHAKE128. The registry is meant as a way to provide better algorithms over time but there's no real need to give implementors a choice. The choice comes later when it has to because a vulnerability is found with SHAKE128 or a better algorithm replaces SHAKE128.

**Comment by pusateri** [comment]
The table should use bits instead of bytes just for flexibility (although it's not likely that an algorithm output length would not be on a byte boundary, we can't predict the future). Section 5.2 (Hash Algorithm Index) currently describes the field in bits.

**Comment by pusateri** [comment]
One more thing, the IANA table should contain a column for the unique section in the document where the value is defined. Multiple values cannot be defined in the same section.

**Comment by timwattenberg** [comment]
Updated the table to reflect your comments.

> One more thing, the IANA table should contain a column for the unique section in the document where the value is defined. Multiple values cannot be defined in the same section.

I'm sorry, I don't really understand what you mean here :) Please just add the column (either in the issue here (you can edit my text via the "three dots"-menu in the upper right), or directly in the draft 😉)

**Comment by pusateri** [comment]
Fixed in cf52f97bd5153b9927104b01ddd3cd98b10717c9
