### ISSUE TITLE
Should there be a withdrawn column in the hash index registry?

### ISSUE THREAD

**Issue by pusateri** [pusateri/draft-pusateri-dnsop-update-timeout#9]

**Comment by pusateri** [comment]
I'm thinking we probably don't need this. We can reconsider later.

**Comment by timwattenberg** [comment]
Maybe a _"current recommendation"_ column would be a better fit? This column would select exactly one entry to be the current (required?) hash algorithm and also identify past recommendations, which should still be supported.

We could extend the _REQUIRED Cryptographic Hash Algorithm_ section to refer to this column.
